name: C/C++ Nigthly macos

on: push
    
#on:
#  push:
#    branches:
#      - Nigthly

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'Nigthly'
    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init
    - name: change date in version
      run: |
        sed "s/+UNKNOWN/_$(date '+%F')/" version.inc > version.date.inc
        mv version.date.inc version.inc

    - name: BuildMacOS arm64
      run: ./BuildMacOS.sh -ix
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_arm64.tar
        path: build/SuperSlicer.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_arm64.dmg
        path: build/SuperSlicer.dmg

    - name: clean
      run: rm -rf build ; rm -rf deps/build

    - name: BuildMacOS amd64
      run: ./BuildMacOS.sh -ia

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_amd64.tar
        path: build/SuperSlicer.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_amd64.dmg
        path: build/SuperSlicer.dmg




